theme = "everforest_dark"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true
mouse = true
scrolloff = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
parents = false
git-ignore = false

[editor.whitespace]
render = "all"

[editor.lsp]
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = [ "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
