theme = "everforest_dark_transparent" # custom theme
[editor]
shell = ["nu"]
auto-save = true
preview-completion-insert = true
bufferline = "always"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
center = ["version-control"]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]

[editor.indent-guides]
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
render = true

[editor.whitespace.render]
tab = "all"
tabpad = "all"
newline = "none"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"C-s" = ":w" # Ctrl-s saves the current file 
down = "no_op" # disable down arrow
up = "no_op" # disable up arrow
y = "yank_main_selection_to_clipboard" # y yanks selection to clipboard
p = "paste_clipboard_before" # p pastes clipboard before 
"ret" = ["open_below", "normal_mode"] # Enter adds line above

# Modified keybindings in Insert mode
[keys.insert]
# left = "no_op"
# right = "no_op"
down = "no_op" # disable down arrow
up = "no_op" # disable up arrow
"A-h" = "move_char_left" # Alt-h moves cursor up
"A-l" = "move_char_right" # Alt-l moves cursor right
"A-k" = "move_line_up" # Alt-k moves cursor up
"A-j" = "move_line_down" # Alt-j moves cursor down
j = { k = "normal_mode" } # jk to enter Normal mode

[keys.select]
y = "yank_main_selection_to_clipboard" # y yanks selection to clipboard
p = "paste_clipboard_before" # p pastes clipboard before
